FROM debian:bullseye as certs
RUN apt update && apt install -y ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY coolshell /cool/shell
EXPOSE 8080/tcp
ENTRYPOINT ["/cool/shell"]